"""discover table

Revision ID: d93cec7e2a9b
Revises: d1c996a76517
Create Date: 2026-01-07 21:19:40.357267

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'd93cec7e2a9b'
down_revision: Union[str, Sequence[str], None] = 'd1c996a76517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
