"""change from id to name

Revision ID: f0791625fd04
Revises: 117f08b52dca
Create Date: 2025-09-20 14:18:39.664702

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0791625fd04"
down_revision: Union[str, Sequence[str], None] = "117f08b52dca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_storage", sa.Column("project_name", sa.String(), nullable=True))
    op.drop_column("file_storage", "project_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_storage", sa.Column("project_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("file_storage", "project_name")
    # ### end Alembic commands ###
