"""index added

Revision ID: 52d7593061e4
Revises: efcaae38d6ac
Create Date: 2025-10-24 12:01:11.889887

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52d7593061e4"
down_revision: Union[str, Sequence[str], None] = "efcaae38d6ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_analysis_results_analysis_id"), "analysis_results", ["analysis_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_results_analysis_id"), table_name="analysis_results")
    # ### end Alembic commands ###
