"""remove tag from discover

Revision ID: 59e186ed94a3
Revises: 05dbe3a7bc6c
Create Date: 2026-01-09 10:40:12.911268

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '59e186ed94a3'
down_revision: Union[str, Sequence[str], None] = '05dbe3a7bc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discover', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discover', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
