"""alembic password management

Revision ID: 63a6c534b9fb
Revises:
Create Date: 2025-09-03 20:38:27.990715

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63a6c534b9fb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bank_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_data",
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("job", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("marital", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("education", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("default", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("balance", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("housing", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("loan", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("contact", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("day", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("month", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("duration", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("campaign", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pdays", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("previous", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("poutcome", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("deposit", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
