"""mobile datatype changed

Revision ID: 7ba4d8e240f1
Revises: 63a6c534b9fb
Create Date: 2025-09-03 20:50:14.887154

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ba4d8e240f1"
down_revision: Union[str, Sequence[str], None] = "63a6c534b9fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tenants", "mobile_no", existing_type=sa.INTEGER(), type_=sa.String(), nullable=False)
    op.create_unique_constraint(None, "tenants", ["mobile_no"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tenants", type_="unique")
    op.alter_column("tenants", "mobile_no", existing_type=sa.String(), type_=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
