"""file storage table updated

Revision ID: 117f08b52dca
Revises: 7ba4d8e240f1
Create Date: 2025-09-18 10:44:29.272451

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "117f08b52dca"
down_revision: Union[str, Sequence[str], None] = "7ba4d8e240f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_storage", sa.Column("project_id", sa.String(), nullable=True))
    op.add_column("file_storage", sa.Column("analysis_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_storage", "analysis_type")
    op.drop_column("file_storage", "project_id")
    # ### end Alembic commands ###
