"""discover table new

Revision ID: a80826a928cc
Revises: d93cec7e2a9b
Create Date: 2026-01-07 21:35:14.252878

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a80826a928cc'
down_revision: Union[str, Sequence[str], None] = 'd93cec7e2a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discover',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('lifecycle_state', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discover_id'), 'discover', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discover_id'), table_name='discover')
    op.drop_table('discover')
    # ### end Alembic commands ###
