"""new column added

Revision ID: da4119d2ab56
Revises: 6f3656245d68
Create Date: 2025-10-15 14:22:13.877178

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da4119d2ab56"
down_revision: Union[str, Sequence[str], None] = "6f3656245d68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis_results", sa.Column("project_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_results", "project_id")
    # ### end Alembic commands ###
