"""analysis id constraints changed

Revision ID: efcaae38d6ac
Revises: da4119d2ab56
Create Date: 2025-10-21 20:30:48.851796

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efcaae38d6ac"
down_revision: Union[str, Sequence[str], None] = "da4119d2ab56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_results_analysis_id"), table_name="analysis_results")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_analysis_results_analysis_id"), "analysis_results", ["analysis_id"], unique=True)
    # ### end Alembic commands ###
