
# LOCAL VALUES

locals {

  # Common Tags - Applied to all resources

  common_tags = {
    Environment = var.environment
    Project     = var.project_name
    ManagedBy   = "Terraform"
    CreatedAt   = timestamp()
    #keynname=> Name = local.pem_key_name
    #vpcname=>Name = "${var.project_name}-vpc
    #igwname=>Name = "${var.project_name}-igw"
  }


  # Network Configuration

  vpc_cidr            = "192.168.0.0/23" # 512 
  public_subnet_cidr  = "192.168.0.0/25" # 128 -5
  private_subnet_cidr = "192.168.1.0/25" # 128 -5


  # PEM Key - Stored locally (generated by tls_private_key resource)
  # The actual key content --> tls_private_key.main

  pem_key_name     = var.key_name
  pem_key_filename = "${var.key_name}.pem"


  # Instance Names

  bastion_name    = "${var.project_name}-bastion-windows"
  windows_vm_name = "${var.project_name}-windows-vm"
  linux_vm_name   = "${var.project_name}-linux-vm"

  # Security Group Ports by OS

  windows_ports = {
    rdp         = 3389
    winrm_http  = 5985
    winrm_https = 5986
  }

  linux_ports = {
    ssh   = 22
    http  = 80
    https = 443
  }

  bastion_ports = { #it will access private windows VM via RDP
    rdp = 3389
  }
}
